### PR TITLE
Kalmanfilter.m

### PR DESCRIPTION
**Pull request by bidh**
Implementation in Objective-C

### CODE REVIEW

**Comment by bidh** [comment]
Here is the implementation for Objective-C

**Comment by wouterbulten** [comment]
Hi! Thanks for your pull request. I am always open to implementations in other languages.

To keep the repo uniform, could you update your implementation to be similar to the others in https://github.com/wouterbulten/kalmanjs/tree/master/contrib?

To be specific, can you take a look at:

- New directory for you implementation
- Examples and author information in a README file (no examples in the class)
- Naming of the class
- Functions (to keep the signature of all implementations as close as possible)

**Comment by wouterbulten** [comment]
@bidh any reason for closing the PR? I would happily merge your class if you are willing to extend it.

**Comment by bidh** [comment]
Hi
I tried to push from my system but not permitted.
Regards

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
